options:
  delay: 3
pages:
  Google:
    url: https://www.google.com/
  Slashdot:
    url: https://slashdot.org/
  Sensu:
    url: http://mysensuserver.mydomain:3000/
    login:
      url: http://mysensuserver.mydomain:3000/
      usernameSelector: user
      passwordSelector: pass
      username: adminuser
      password: adminpassword
